# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lab/Documents/EmbeddedSystems/Wednesday/AidanThomasTinu/SoC/DES_SoC/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword.xci
# IP: The module: 'blk_mem_4Kword' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lab/Documents/EmbeddedSystems/Wednesday/AidanThomasTinu/SoC/DES_SoC/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_4Kword'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/lab/Documents/EmbeddedSystems/Wednesday/AidanThomasTinu/SoC/DES_SoC/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword.xci
# IP: The module: 'blk_mem_4Kword' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lab/Documents/EmbeddedSystems/Wednesday/AidanThomasTinu/SoC/DES_SoC/Hardware/DemoSystem.srcs/sources_1/ip/blk_mem_4Kword/blk_mem_4Kword_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_4Kword'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
