# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lab/Documents/EmbeddedSystems/Wednesday/AidanThomasTinu/SoC/DES_SoC/Hardware/Constraint/Nexys4_SoC.xdc

# IP: ip/blk_mem_8Kword/blk_mem_8Kword.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_8Kword || ORIG_REF_NAME==blk_mem_8Kword}]

# XDC: ip/blk_mem_8Kword/blk_mem_8Kword_ooc.xdc
